---
# event types need to be defined in this file to be handled by spatula.
# this file is used to define configuration options that change how spatula
# dispatches and pre-processes the event data

# spatula internal events
:spatula: {}

# slack events (these should NOT be prefixed with `slack_`. Spatula will add that prefix when dispatching them internally)
:slack:
     :message:
          :preprocess:
               :text:
                    :tokenize: true
                    :unescape: true
                    :syllabify: true
                    :mentions: true
               :channel:
                    :conversation_name: true
               :user:
                    :user_name: true
          :subtypes:
               :bot_message: {}
               :file_comment: {}
               :me_message: {}
               :message_replied: {}
               :channel_archive:
                    :preprocess: false
               :channel_join:
                    :preprocess: false
               :channel_leave:
                    :preprocess: false
               :channel_join:
                    :preprocess: false
               :channel_name:
                    :preprocess: false
               :channel_purpose:
                    :preprocess: false
               :channel_topic:
                    :preprocess: false
               :channel_unarchive:
                    :preprocess: false
               :file_mention:
                    :preprocess: false
               :file_share:
                    :preprocess: false
               :group_archive:
                    :preprocess: false
               :group_join:
                    :preprocess: false
               :group_leave:
                    :preprocess: false
               :group_name:
                    :preprocess: false
               :group_purpose:
                    :preprocess: false
               :group_topic:
                    :preprocess: false
               :group_unarchive:
                    :preprocess: false
               :message_changed:
                    :preprocess: false
               :message_deleted:
                    :preprocess: false
               :pinned_item:
                    :preprocess: false
               :reply_broadcast:
                    :preprocess: false
               :unpinned_item:
                    :preprocess: false
     :accounts_changed: {}
     :bot_added: {}
     :bot_changed: {}
     :channel_archive: {}
     :channel_created: {}
     :channel_deleted: {}
     :channel_history_changed: {}
     :channel_joined: {}
     :channel_left: {}
     :channel_marked: {}
     :channel_rename: {}
     :channel_unarchive: {}
     :commands_changed: {}
     :dnd_updated: {}
     :dnd_updated_user: {}
     :email_domain_changed: {}
     :emoji_changed: {}
     :file_change: {}
     :file_comment_added: {}
     :file_comment_deleted: {}
     :file_comment_edited: {}
     :file_created: {}
     :file_deleted: {}
     :file_public: {}
     :file_shared: {}
     :file_unshared: {}
     :goodbye: {}
     :group_archive: {}
     :group_close: {}
     :group_history_changed: {}
     :group_joined: {}
     :group_left: {}
     :group_marked: {}
     :group_open: {}
     :group_rename: {}
     :group_unarchive: {}
     :hello: {}
     :im_close: {}
     :im_created: {}
     :im_history_changed: {}
     :im_marked: {}
     :im_open: {}
     :manual_presence_change: {}
     :member_joined_channel: {}
     :member_left_channel: {}
     :pin_added: {}
     :pin_removed: {}
     :pref_change: {}
     :presence_change: {}
     :presence_sub: {}
     :reaction_added: {}
     :reaction_removed: {}
     :reconnect_url: {}
     :star_added: {}
     :star_removed: {}
     :subteam_created: {}
     :subteam_members_changed: {}
     :subteam_self_added: {}
     :subteam_self_removed: {}
     :subteam_updated: {}
     :team_domain_change: {}
     :team_join: {}
     :team_migration_started: {}
     :team_plan_change: {}
     :team_pref_change: {}
     :team_profile_change: {}
     :team_profile_delete: {}
     :team_profile_reorder: {}
     :team_rename: {}
     :user_change: {}
     :user_typing: {}

...
